---
title: "lab5 jiun"
author: "Jiun"
date: "9/21/2020"
output: html_document
---
```{r, fig.height=10}
#2 Revise the above example for joining tables using 6/13/2020 and 9/13/2020. Plot the data as a bar plot. Make sure your graph looks nice in the report by adjusting the height in the R code chunk header.

library(tidyverse)
Confirmed_State_6_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
str(Confirmed_State_6_13)
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
str(Confirmed_State_9_13)
setdiff(Confirmed_State_6_13$Province_State, Confirmed_State_9_13$Province_State)
Confirmed_State_9_13 <- Confirmed_State_6_13 %>% 
  filter(Province_State != "Recovered") 
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
tail(Confirmed_State_6_13_9_13_joined, 5)
which(is.na(Confirmed_State_6_13_9_13_joined))
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_6_13_2020 = 0))
head(Confirmed_State_6_13_9_13_joined)
which(is.na(Confirmed_State_6_13_9_13_joined))
Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
              pivot_longer(-c(Province_State), names_to = "Date", values_to = "Confirmed")
#3 Add more informative x and y labels and a title to the above graph in Ex2.
ggplot(data = Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed, y = Province_State), color="Date") + geom_bar (stat='identity') + labs( x = "Confirmed " , y = "Province / State") 

```
```{r}
#4 Using the time series data. Make a plot of the total number of confirmed deaths per day worldwide
library(lubridate)
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
head(time_series_confirmed)
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 
head(time_series_confirmed_long)
 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
 time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
which(is.na(time_series_long_joined$Confirmed))
which(is.na(time_series_long_joined$Deaths))
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
#World wide COVID-19 confirmed death per day point plot
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("World wide COVID-19 confirmed death per day")

#5 Use Mutate to make a new column with deaths/confirmed cases (Hint: this might be best done after joining the tables, but before pivoting longer).
#6 Plot US deaths/confirmed cases per day.

#US Deaths per day point plot
time_series_long_joined %>% 
 group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US Deaths per day")
```

```{r}
#7 - Make a single graph with from the times series data with the 10 countries with the highest death total
deathtotal<-subset(time_series_long_joined, Date=="2020-09-20")
descdeath<-deathtotal%>%arrange(desc(Deaths))%>%slice(1:10)
ggplot(data = descdeath, aes(x = Country_Region, y = Deaths, color = Country_Region))  + geom_point() + theme_classic()+theme(legend.position="none") + labs( x = "Country" , y = "Deaths") + ggtitle("10 countries with the highest death total")
```
```{r, fig.height=6}
#8 Using Facet_Wraps make a graph from the times series data with the 10 countries with the hightest death total. Format the table to look nice in the report by changing the number of rows in your graph and/or adjusting the height in the R code chunk header.

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil", "India, Mexico",
                                "United Kingdom","Italy", "Peru", "France", "Spain", "Iran")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```
```{r}
#9 Using Facet_Wraps make a graph from the times series data for confirmed cases for all US states and territories. Format the table to look nice in the report by changing the number of rows in your graph and/or adjusting the height in the R code chunk header.

time_series_long_joinedUS<-subset(time_series_long_joined, Country_Region == "US")
time_series_long_joinedUS%>%
  group_by(Province_State, Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    ggplot(aes(x = Date,  y = Confirmed)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths") + facet_wrap(facets = vars(Province_State))
```

```{r, fig.height=6}
#8 Using Facet_Wraps make a graph from the times series data with the 10 countries with the hightest death total. Format the table to look nice in the report by changing the number of rows in your graph and/or adjusting the height in the R code chunk header.

time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil", "India, Mexico",
                                "United Kingdom","Italy", "Peru", "France", "Spain", "Iran")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    theme_dark()+
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```


